export const FETCHCRIMES = 'FETCHCRIMES';
export const RECEIVECRIMES = 'RECEIVECRIMES';
export const FETCHARRESTS = 'FETCHARRESTS';
export const RECEIVEARRESTS = 'RECEIVEARRESTS';
export const UPDATEARREST = 'UPDATEARREST';
export const EDITARREST = 'EDITARREST';
